services:
  - type: web
    name: ml-project
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn application:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
